CREATE DATABASE accounts;
CREATE USER 'TDBUSER'@'%' IDENTIFIED BY 'TDBPASS';
CREATE USER 'TDBUSER'@'localhost' IDENTIFIED BY 'TDBPASS';
use accounts;
GRANT ALL PRIVILEGES ON accounts.* TO 'TDBUSER'@'%';
GRANT ALL PRIVILEGES ON accounts.* TO 'TDBUSER'@'localhost';
